"""
Django settings for faq_project project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c92^k!j264!94l3rh)!hul6x1hh1fo%k768rmx^1=!gl8gtx2x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'ckeditor',
    'rest_framework',
    'faq',
]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'faq.exception_handler.custom_exception_handler',
}

LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
    ('bn', 'Bengali'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('zh-hans', 'Simplified Chinese'),
    ('ja', 'Japanese'),
    ('ru', 'Russian'),
    ('ar', 'Arabic'),
    ('pt', 'Portuguese'),
    ('it', 'Italian'),
    ('ko', 'Korean'),
    ('nl', 'Dutch'),
    ('tr', 'Turkish'),
    ('pl', 'Polish'),
    ('sv', 'Swedish'),
    ('fi', 'Finnish'),
    ('no', 'Norwegian'),
    ('da', 'Danish'),
    ('el', 'Greek'),
    ('he', 'Hebrew'),
    ('th', 'Thai'),
    ('vi', 'Vietnamese'),
    ('uk', 'Ukrainian'),
    ('cs', 'Czech'),
    ('ro', 'Romanian'),
    ('hu', 'Hungarian'),
    ('id', 'Indonesian'),
    ('ms', 'Malay'),
    ('fil', 'Filipino'),
    ('sw', 'Swahili'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('ur', 'Urdu'),
    ('fa', 'Persian'),
    ('si', 'Sinhala'),
    ('ne', 'Nepali'),
    ('my', 'Burmese'),
    ('km', 'Khmer'),
    ('lo', 'Lao'),
    ('bo', 'Tibetan'),
    ('dz', 'Dzongkha'),
    ('ml', 'Malayalam'),
    ('kn', 'Kannada'),
    ('gu', 'Gujarati'),
    ('pa', 'Punjabi'),
    ('or', 'Odia'),
    ('as', 'Assamese'),
    ('mr', 'Marathi'),
    ('sa', 'Sanskrit'),
    ('sd', 'Sindhi'),
    ('ks', 'Kashmiri'),
    ('mai', 'Maithili'),
    ('mni', 'Manipuri'),
    ('sat', 'Santali'),
    ('kok', 'Konkani'),
    ('doi', 'Dogri'),
    ('brx', 'Bodo'),
    ('lus', 'Mizo'),
    ('kha', 'Khasi'),
    ('grt', 'Garo'),
    ('nic', 'Nicobarese'),
    ('sit', 'Sino-Tibetan'),
    ('tib', 'Tibetan'),
    ('mn', 'Mongolian'),
    ('ug', 'Uyghur'),
    ('kk', 'Kazakh'),
    ('ky', 'Kyrgyz'),
    ('uz', 'Uzbek'),
    ('tk', 'Turkmen'),
    ('az', 'Azerbaijani'),
    ('ka', 'Georgian'),
    ('hy', 'Armenian'),
    ('be', 'Belarusian'),
    ('mk', 'Macedonian'),
    ('sr', 'Serbian'),
    ('hr', 'Croatian'),
    ('sl', 'Slovenian'),
    ('sq', 'Albanian'),
    ('mt', 'Maltese'),
    ('ga', 'Irish'),
    ('cy', 'Welsh'),
    ('eu', 'Basque'),
    ('ca', 'Catalan'),
    ('gl', 'Galician'),
    ('af', 'Afrikaans'),
    ('zu', 'Zulu'),
    ('xh', 'Xhosa'),
    ('st', 'Southern Sotho'),
    ('tn', 'Tswana'),
    ('ts', 'Tsonga'),
    ('ss', 'Swati'),
    ('ve', 'Venda'),
    ('nr', 'Ndebele'),
    ('sn', 'Shona'),
    ('lg', 'Ganda'),
    ('rw', 'Kinyarwanda'),
    ('ny', 'Chichewa'),
    ('mg', 'Malagasy'),
    ('yo', 'Yoruba'),
    ('ha', 'Hausa'),
    ('ig', 'Igbo'),
    ('ff', 'Fulah'),
    ('wo', 'Wolof'),
    ('so', 'Somali'),
    ('om', 'Oromo'),
    ('am', 'Amharic'),
    ('ti', 'Tigrinya'),
    ('aa', 'Afar'),
    ('ss', 'Sidamo'),
    ('wal', 'Wolaytta'),
    ('sid', 'Sidamo'),
    ('orm', 'Oromo'),
    ('som', 'Somali'),
    ('tir', 'Tigrinya'),
    ('aar', 'Afar'),
    ('ssy', 'Saho'),
    ('ssw', 'Swati'),
    ('nso', 'Northern Sotho'),
    ('tso', 'Tsonga'),
    ('ven', 'Venda'),
    ('nbl', 'Southern Ndebele'),
    ('xho', 'Xhosa'),
    ('zul', 'Zulu'),
    ('tsn', 'Tswana'),
    ('sot', 'Southern Sotho'),
    ('tso', 'Tsonga'),
    ('ven', 'Venda'),
    ('nbl', 'Southern Ndebele'),
    ('xho', 'Xhosa'),
    ('zul', 'Zulu'),
    ('tsn', 'Tswana'),
    ('sot', 'Southern Sotho'),
]
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
    },
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "faq_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "faq_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
